### PR TITLE
Add the mtcli bundle validate command to validate local bundle dirs.

### PR DESCRIPTION
**Pull request by sugarraysam**
Creating a new `mtcli validate-bundle <bundle_path>` command to mimic `opm alpha bundle validate --tag <image>` but using local directory path.

### CODE REVIEW

**Comment by sandhyadalavi** [comment]
can we add the test? it will be very similar to this? https://github.com/mt-sre/addon-metadata-operator/blob/master/integration/mtcli/list_bundles_test.go

**Comment by sugarraysam** [comment]
Thanks for your feedback @sandhyadalavi . I think Im actually going to trash this PR, and tackle the problem at the source, meaning write a new containerregistry implementation that first looks for locally built images, will also solve the `list-bundles` issue.

**Comment by sugarraysam** [comment]
Changes !
- added a bunch of testdata: `internal/testdata/bundles/*`
- refactored cli to have subcommands `mtcli bundle [subcommand]` + `mtcli list [subcommand]`
- added e2e test

**Review by sandhyadalavi — APPROVED** [review]
lgtm

**Pull request merged**
