### PR TITLE
Refactoring AM0003 code according to the current directory structure.

### PR DESCRIPTION
**Pull request by Ankit152**
# AM0003

## Description

Refactoring Sam's PR for `AM0003` validator according to the current directory structure of `AMO`.

### CODE REVIEW

**Comment by Ajpantuso** [comment]
The rebase is good. Tests will need to be moved over and the original functionality (especially regarding semver validation) needs to be updated as well. Instead of leaving comments here I performed my own [refactor](https://github.com/Ajpantuso/addon-metadata-operator/commit/dfacfff47591622b4c8e11fd58deaf1d02d5e164) which can review to bring this PR up-to-date as well.

**Comment by Ankit152** [comment]
Thanks a ton Andrew! :)
I was going through the code, shouldn't [this](https://github.com/Ajpantuso/addon-metadata-operator/commit/dfacfff47591622b4c8e11fd58deaf1d02d5e164#diff-740c99af10f88ba3d3b6b25f20e98d262666df4ccfb8f005f115f67e9ad3c392L30) be `replaces: reference-addon.0.1.5` in place of `replaces: reference-addon.v0.1.5`.
Let me know what do you think.

**Comment by Ajpantuso** [comment]
> Thanks a ton Andrew! :) I was going through the code, shouldn't [this](https://github.com/Ajpantuso/addon-metadata-operator/commit/dfacfff47591622b4c8e11fd58deaf1d02d5e164#diff-740c99af10f88ba3d3b6b25f20e98d262666df4ccfb8f005f115f67e9ad3c392L30) be `replaces: reference-addon.0.1.5` in place of `replaces: reference-addon.v0.1.5`. Let me know what do you think.

`csv_semver_invalid.yaml` is a test fixture which should fail validation due to a `v` prefixed version, or any invalid semantic version, which is why it was not changed to `0.1.5`. Originally we permitted `v` prefixed versions since they were accepted in `OPM 1.15.1`, but when Sam attempted to bump the OPM version so that we could inspect bundle annotations we found that OPM introduced a breaking change which enforced strict [semver](https://semver.org/).

**Review by Ajpantuso — APPROVED** [review]
LGTM, hold until #69 is completed

**Comment by Ankit152** [comment]
Welcome Andrew!

**Pull request merged**
